front:
  build: .
  ports:
    - "80:80"
    - "443:443"

  links:
    - mysql:mysql

  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor
  environment:
    DNSDOCK_ALIAS: 'front.docker'

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
